### PR TITLE
optimize for satellites

### PR DESCRIPTION
**Pull request by idelvall**
This PR:
- Collapses the Earthly targets run on `ci.yaml` into a new `+ci` target, so only one GH runner is needed for them
- Makes use of https://github.com/earthly/lib/blob/main/rust/Earthfile#L10 to cache cargo dependency downloads and compilations across builds
- Runs earthly in a dedicated satellite, so cache is maintained across different GH action runs

As a result, this PR reduces GH actions build time from around 7m to 1.5m for the most likely scenario of only source code changing

### CODE REVIEW

**Comment by idelvall** [comment]
Refactored the code to use the new version `github.com/earthly/lib/rust:2.1.0`, that simplifies its interface to the minimum and adds caching to the cargo git metadata.

**Comment by idelvall** [comment]
Squashed all commits, this should be ready.
I would appreciate a review. Thanks guys!

**Comment by idelvall** [comment]
Just moved `cargo-deny` also to run in Earthly. 
@expressvpn-mariappan-r please check if this is aligned with you latest changes (i think it is 🙂), thanks!

**Comment by xv-andre-l** [comment]
FYI @idelvall this PR was closed because we wanted to rewrite the git history and get rid of some tarballs to save space.   We still want your Satellites work! Let's work together to rebase it back on the latest `main` branch

**Pull request closed without merging**
