### PR TITLE
README: Add deprecation banner.

### PR DESCRIPTION
**Pull request by xv-ian-c**
## Description

The contents of this repo is moving to the wolfssl repo (see https://github.com/expressvpn/wolfssl/pull/39) which will be renamed `wolfssl-rs`.

Note that the link added here will not be valid until that renaming has been completed.

## Motivation and Context

We would like to get rid of the committed/vendors tarballs, since they are exploding the size of the repo, and switch to using submodules instead. We tried this in https://github.com/expressvpn/wolfssl-sys/pull/53 but it turned out to be more complicated than anticipated.

Instead we will switch to a single `wolfssl-rs` workspace repository.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All active GitHub checks are passing  
- [ ] The correct base branch is being used, if not `main`

### CODE REVIEW

**Review by kp-mariappan-ramasamy — APPROVED** [review]
LGTM as long as we merge this, after the repo renaming

**Comment by xv-ian-c** [comment]
Our IAC as code will archive this repo in the same changeset as the rename of `wolfssl` to `wolfssl-rs`, so we need to merge this right before we apply the IAC change since we can't merge it after archiving. It should all happen in quick succession though.

**Comment by kp-mariappan-ramasamy** [comment]
Should have been two iac PRs for the transition and to avoid race condition.
One to rename and one to archive. But think, should be fine since invalid link may be for few min/hour

**Comment by xv-ian-c** [comment]
Invalid link will be minutes, but it turns out that we had to split anyway for other IAC related reasons so we'll do the rename before merging this.

**Review by xv-pete-m — APPROVED** [review]

**Pull request merged**
